### ISSUE TITLE
cant support tsconfig.compilerOptions.paths?

### ISSUE THREAD

**Issue by takegine** [egoist/rollup-plugin-esbuild#363] opened 2023-03-23 12:46 UTC
![image](https://user-images.githubusercontent.com/64788603/227206923-f0e7324e-79f5-4eff-ae0f-e0193a33597c.png)

https://github.com/evanw/esbuild/issues/3017

**Comment by sxzz** [comment] 2023-09-20 14:50
Duplicate of #70

**Closed by sxzz** 2023-09-20 14:50 UTC
