### ISSUE TITLE
inject is not working

### ISSUE THREAD

**Issue by takegine** [egoist/rollup-plugin-esbuild#340] opened 2022-06-02 09:20 UTC
i had try 
```javascript
esbuild({
    inject:['toolCode/react.ts']
})
```

```typescript
// toolCode/react.ts
import * as React from 'react'
export { React }
```

but i got error
![image](https://user-images.githubusercontent.com/64788603/171597745-e555946c-f0a6-44e5-93d3-508ef9a2cb41.png)

i need build include 'react' as React and ’@demon673/react-panorama‘ as ReactPanorama
if i build without those `node_modules`，it can run in engine

![image](https://user-images.githubusercontent.com/64788603/171597972-5c2dbf0f-74c2-4b0c-b6df-3a02740009e1.png)

**Comment by sxzz** [comment] 2023-09-20 15:30
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by sxzz** 2023-09-20 15:30 UTC
